from active_learning_ts.experiments.experiment_runner import ExperimentRunner
from blueprints.custom_mean_gaussian_process_blueprint import CustomMeanGaussianProcessBlueprint

runner = ExperimentRunner(experiment_blueprints=[CustomMeanGaussianProcessBlueprint], log=True)
runner.run()
